name: 'oscar_project'
version: '1.0.0'
profile: 'oscar_project'

# Diretórios padrão do dbt
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuração de Models
models:
  oscar_project:
    +tags: ['poc']
        
    raw:
      +materialized: table
      +schema: raw
      +tags: ["raw"]
      
    stage:
      +materialized: view      
      +schema: stage
      +tags: ["stage"]
      
    mart:
      +materialized: table
      +transient: false
      +schema: mart
      +tags: ["mart"]

# CONFIGURAÇÃO DO SEED (aux_nomes.csv)
seeds:
  oscar_project:
    # O seed será criado no schema de RAW do seu Snowflake
    +schema: raw
    +quote_columns: false
    config:
      # Definimos varchar sem limite (ou alto) para evitar erro no campo alternative_names
      column_types:
        alternative_names: varchar
        first_name: varchar
        group_name: varchar
        classification: varchar(10)