name: 'oscar_project'
version: '1.0.0'
profile: 'oscar_project'

# Diretórios padrão do dbt
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuração de Models
models:
  oscar_project:
    +tags: ['poc']
   
    raw:
      +materialized: table
      +schema: raw
      +tags: ["raw"]
      
    stage:
      +materialized: table      
      +schema: stage
      +tags: ["stage"]
      
    marts:
      +materialized: table
      +transient: false
      +schema: mart
      +tags: ["mart"]

seeds:
  oscar_project:
    # Configurações globais (aplicam-se a todos os seeds)
    +schema: raw_seed
    +quote_columns: false

    # 1. Configuração para aux_nomes
    aux_nomes:
      +column_types:
        alternative_names: varchar
        first_name: varchar
        group_name: varchar
        classification: varchar(10)

    # 2. Configuração para aux_feriados
    aux_feriados:
      +column_types:
        data: varchar 

    # 3. Demais arquivos (configurações diretas)
    aux_emails_lojas:
      +enabled: true

    aux_gestores:
      +enabled: true

    aux_shop_rua_lojas:
      +enabled: true

    aux_status_funcionamento_lojas:
      +enabled: true

vars:
  raw_json_copy:
    stage_base: "@RAW.STAGE_SUPPLYCHAIN/landing"
    file_format_name: "RAW.PARQUET_FILE_FORMAT"
    force_copy: false
    record_source: "mstore"

    tables:
      - source_name: "raw_json"
        target_table: "jsn_mstore_enriched_gender_classifier"
        s3_folder: "table1"
        # pattern: ".*\\.parquet"   # opcional

      - source_name: "raw_json"
        target_table: "jsn_mstore_history_estoque"
        s3_folder: "table2"


