version: 2

models:

  - name: dim_cliente
    description: Tabela de clientes.
    columns:
      - name: sk_cliente
        description: Chave primária da tabela.
      - name: idcliente
        description: Chave única do cliente.
      - name: num_cpf
        description: CPF do cliente.
      - name: nm_nome
        description: Nome do cliente.
      - name: ds_genero
        description: Gênero do cliente.
      - name: dt_datanascimento
        description: Data de nascimento do cliente.
      - name: num_idade
        description: Idade do cliente.
      - name: ds_faixa_etaria
        description: Faixa etária em que o cliente se enquadra.
      - name: ordem_faixa_et
        description: Campo para ordernar numericamente o campo ds_faixa_etaria.
      - name: num_celular
        description: Número do celular do cliente.
      - name: ds_email
        description: E-mail do cliente.
      - name: nk_idendereco
        description: Chave única do endereço do cliente.
      - name: num_cep
        description: CEP do cliente.
      - name: ds_logradouro
        description: Logradouro do cliente.
      - name: num_numero
        description: Número da residência do cliente.
      - name: ds_bairro
        description: Bairro do cliente.
      - name: ds_cidade
        description: Cidade do cliente.
      - name: ds_estado
        description: Estado do cliente.
      - name: ds_e_funcionario
        description: Flag se o registro é de um funcionário.
      - name: ds_canal_venda
        description: Classifica o cliente de acordo com os canais onde ele fez uma compra (Online, Offline ou Ambos).

  - name: fat_venda
    description: Tabela de vendas.
    columns:
      - name: ds_status
        description: Status do pedido.
      - name: dt_data
        description: Data do pedido.
      - name: ds_canal_venda
        description: Identificação do canal de entrada do pedido.
      - name: nk_idestabelecimento
        description: Chave única do estabelecimento de faturamento.
      - name: nk_idestabelecimentovendedor
        description: Chave única do estabelecimento de venda.
      - name: nk_idorcamento
        description: Chave única do orçamento.
      - name: nk_idproduto
        description: Chave única do produto.
      - name: nk_idvendedor
        description: Chave única do vendedor.
      - name: nk_id_pedido_vtex
        description: Chave única do pedido da Vtex.
      - name: qt_produtovendido
        description: Quantidade de itens na venda.
      - name: ds_statusproduto
        description: Classificação do status em estoque do produto.
      - name: nm_host
        description: Parceiro integrador do market place responsável pela venda.
      - name: vl_cashback
        description: Valor do cashback.
      - name: vl_cupom
        description: Valor do cupom.
      - name: vl_desconto
        description: Valor do desconto.
      - name: vl_desconto_funcionario
        description: Valor do desconto de funcionário.
      - name: vl_kit_desconto
        description: Valor do kit de desconto.
      - name: vl_frete
        description: Valor total do frete.
      - name: vl_custo
        description: Valor total do custo do produto.
      - name: vl_venda
        description: Valor total da venda do produto.
      - name: vl_vendaliquida
        description: Valor total da venda do produto deduzindo os descontos.

  - name: dim_calendario
    description: Tabela que contém informações relacionadas ao calendario
    columns:
      - name: sk_data
        description: Chave única identificadora para cada registro no calendário.
      - name: data
        description: Representa a data do calendário.
      - name: dia_mes
        description: Indica o dia do mês no calendário.
      - name: n_dia_semana
        description: Número correspondente ao dia da semana no calendário.
      - name: dia_do_ano
        description: Representa o dia do ano no calendário.
      - name: ultimo_dia_mes
        description: Indica o último dia do mês no calendário.
      - name: nomes_mes
        description: Nome completo do mês no calendário.
      - name: nome_mes_curto
        description: Nome curto do mês no calendário.
      - name: numero_mes
        description: Número do mês no calendário.
      - name: primeiro_dia_mes
        description: Indica o primeiro dia do mês no calendário.
      - name: trimestre
        description: Indica o trimestre ao qual a data pertence no calendário.
      - name: data_final_semana
        description: Indica a data final da semana no calendário.
      - name: semana_ano
        description: Número correspondente à semana do ano no calendário.
      - name: data_comeco_semana
        description: Indica a data de início da semana no calendário.
      - name: ultimo_dia_ano
        description: Indica o último dia do ano no calendário.
      - name: ano
        description: Representa o ano no calendário.
      - name: primeiro_dia_ano
        description: Indica o primeiro dia do ano no calendário.
      - name: nome_dia_semana
        description: Nome do dia da semana no calendário.
      - name: nome_dia_semana_curto
        description: Nome curto do dia da semana no calendário.
      - name: semestre
        description: Indica o semestre ao qual a data pertence no calendário.
      - name: quadrimestre
        description: Indica o quadrimestre ao qual a data pertence no calendário.
      - name: bimestre
        description: Indica o bimestre ao qual a data pertence no calendário.

  - name: dim_funcionario
    description: Tabela que indica informações sobre os funcionários
    columns:
      - name: sk_funcionário
        description: Chave unica identificadora do funcionário.
      - name: num_tempo_de_empresa
        description: Indica o tempo de empresa do funcionário.
      - name: num_idade_atual
        description: Indica a idade atual do funcionário.
      - name: num_cpf
        description: Indica o cpf do funcionário.
      - name: num_cep
        description: Indica o cep do funcionário.
      - name: nm_numero
        description: Indica o numero do funcionário.
      - name: nm_nome
        description: Indica o nome do funcionário.
      - name: nm_nome_fantasia_estabelecimento
        description: Indica o nome fantasia do estabelecimento.
      - name: nk_idfuncionário
        description: Indica o ID do funcionário.
      - name: id_usuario
        description: Indica o ID do usuario.
      - name: ds_uf
        description: Indica a unidade federal onde está localizado o funcionário.
      - name: ds_logradouro
        description: Indica o logradouro do funcionário.
      - name: ds_genero
        description: Indica o genero do funcionário.
      - name: ds_estadocivil
        description: Indica o estado civil do funcionário.
      - name: ds_bairro
        description: Indica o bairro do funcionário.
      - name: ds_atividade
        description: Indica a atividade / cargo do funcionário.

  - name: dim_loja
    description: Tabela que indica informações sobre as lojas
    columns:
      - name: sk_loja
        description: Chave unica identificadora da loja.
      - name: num_numero
        description: Indica o numero da loja.
      - name: num_inscricaoestadual
        description: Indica a inscrição estadual da loja.
      - name: num_cnpj
        description: Indica o CNPJ da loja.
      - name: num_cep
        description: Indica o CEP da loja.
      - name: nm_razaosocial
        description: Indica a razão social da loja.
      - name: nm_nomefantasia
        description: Indica o nome fantasia da loja.
      - name: nk_idunidadenegocio
        description: Indica o ID da unidade de negocio.
      - name: nk_idestabelecimento
        description: Indica o ID do estabelecimento.
      - name: ds_unidadenegocio
        description: Indica a unidade de negocio.
      - name: ds_uf
        description: Indica a uf da loja.
      - name: ds_status
        description: Indica o status da loja.
      - name: ds_sigla
        description: Indica a sigla da loja.
      - name: ds_logradouro
        description: Indica o logradouro da loja.
      - name: ds_localidade
        description: indica a locidade da loja.
      - name: ds_bairro
        description: indica o bairro da loja.

  - name: dim_gestores
    description: Tabela que indica informações sobre os gestores
    columns:
      - name: sigla
        description: Indica a sigla associada ao gestor.
      - name: store
        description: Indica a loja do gestor.
      - name: director
        description: Indica o diretor associado ao gestor.
      - name: regional
        description: Indica o regional associado ao gestor.
      - name: gerente
        description: Indica o gerente associado ao gestor.

  - name: dim_produto
    description: Tabela que indica informações sobre o produto
    columns:
      - name: sk_produto
        description: Chave única identificadora do produto, utilizada como referência única na tabela.
      - name: nk_produto
        description: Identificador único do produto, utilizado para referência externa.
      - name: nm_nome
        description: Nome do produto que o identifica de maneira amigável e descritiva.
      - name: ds_departamento
        description: Departamento ao qual o produto pertence, indicando sua categoria principal.
      - name: ds_grupo_produto
        description: Grupo ao qual o produto está associado, fornecendo uma classificação adicional.
      - name: ds_familia
        description: Família à qual o produto pertence, fornecendo uma classificação hierárquica.
      - name: ds_subfamilia
        description: Subfamília à qual o produto pertence, refinando ainda mais sua classificação.
      - name: ds_secao
        description: Seção específica à qual o produto está relacionado, fornecendo uma categorização mais detalhada.
      - name: ds_marca
        description: Marca associada ao produto, indicando sua origem ou fabricante.
      - name: ds_material
        description: Material utilizado na fabricação do produto, fornecendo informações sobre sua composição.
      - name: ds_cor
        description: Cor predominante do produto, auxiliando na identificação visual.
      - name: ds_tamanho
        description: Tamanho do produto, quando aplicável, fornecendo informações sobre suas dimensões.
      - name: vl_precovenda
        description: Valor de venda do produto, indicando seu preço de comercialização.
      - name: ds_status
        description: Status atual do produto, indicando se está ativo, inativo ou outra condição.
      - name: ds_foradelinha
        description: Informação sobre se o produto está fora de linha, indicando se ainda está disponível para venda.
      - name: ds_ecommerce
        description: Indicação de participação do produto em atividades de comércio eletrônico.
      - name: ds_produtogenerico
        description: Indicação de se o produto é genérico, ou seja, não possui uma marca específica associada.
      - name: ds_produtoespecifico
        description: Indicação de se o produto é específico, ou seja, possui características distintas e únicas.

  - name: fat_troca
    description: Tabela que registra informações sobre trocas de produtos
    columns:
      - name: id_orcamento_dd
        description: Identificador único do orçamento associado à troca.
      - name: ds_status
        description: Status atual da troca, indicando se está em processamento, concluída, etc.
      - name: sk_dt_troca
        description: Chave única identificadora da data associada à troca.
      - name: sk_vendedor
        description: Chave única identificadora do vendedor associado à troca.
      - name: sk_loja
        description: Chave única identificadora da loja associada à troca.
      - name: sk_lojavendedor
        description: Chave única identificadora da loja do vendedor associada à troca.
      - name: sk_cliente
        description: Chave única identificadora do cliente associado à troca.
      - name: sk_produto
        description: Chave única identificadora do produto associado à troca.
      - name: qtd_produto_trocado
        description: Quantidade do produto efetivamente trocada.
      - name: vlr_venda_troca
        description: Valor de venda relacionado à troca do produto.
      - name: vlr_venda_custo
        description: Valor de custo relacionado à troca do produto.
      - name: flg_status_produto
        description: Status atual do produto associado à troca.
      - name: id_pedido_vtex_dd
        description: Identificador único do pedido na plataforma VTEX associado à troca.
      - name: nm_host
        description: Nome do host relacionado à troca.
      - name: ds_canal_venda
        description: Canal de venda associado à troca, indicando a origem da transação.

  - name: fat_venda_liquida
    description: Tabela que registra informações sobre vendas líquidas de produtos
    columns:
      - name: tipo
        description: Tipo de transação, indicando se é uma venda, troca, etc.
      - name: sk_data
        description: Chave única identificadora da data associada à venda líquida.
      - name: sk_vendedor
        description: Chave única identificadora do vendedor associado à venda líquida.
      - name: sk_loja
        description: Chave única identificadora da loja associada à venda líquida.
      - name: sk_loja_vendedor
        description: Chave única identificadora da loja do vendedor associada à venda líquida.
      - name: sk_cliente
        description: Chave única identificadora do cliente associado à venda líquida.
      - name: sk_produto
        description: Chave única identificadora do produto associado à venda líquida.
      - name: id_orcamento_dd
        description: Identificador único do orçamento associado à venda líquida.
      - name: ds_status
        description: Status atual da venda líquida, indicando se está em processamento, concluída, etc.
      - name: qtd_vendida
        description: Quantidade do produto efetivamente vendida.
      - name: vlr_venda_liquida
        description: Valor líquido da venda do produto.
      - name: vlr_venda_custo
        description: Valor de custo relacionado à venda do produto.
      - name: flg_status_produto
        description: Status atual do produto associado à venda líquida.
      - name: id_pedido_vtex_dd
        description: Identificador único do pedido na plataforma VTEX associado à venda líquida.
      - name: nm_host
        description: Nome do host relacionado à venda líquida.
      - name: ds_canal_venda
        description: Canal de venda associado à venda líquida, indicando a origem da transação.
      - name: flag_primeira_compra
        description: Flag que define a primeira compra do cliente.
      - name: ds_faixa_valor
        description: Classifica o valor da venda líquida em faixas.


