{{
  config(
    materialized = 'view'
  ) 
}}

WITH raw_data AS (
    SELECT
        JSON_DATA,                  -- Campo VARIANT contendo o JSON completo
        S3_FILE_NAME,              -- Nome do arquivo S3 de origem
        S3_FILE_ROW_NUMBER,        -- Número da linha no arquivo original
        S3_FILE_LAST_MODIFIED,     -- Timestamp de modificação do arquivo S3
        LOAD_TIMESTAMP_UTC,        -- Timestamp de quando foi carregado no Snowflake
        RECORD_SOURCE              -- Identificador da fonte do registro
    FROM {{ source('raw_json', 'jsn_mstore_t_cliente') }}
)

SELECT
    -- Colunas extraídas do JSON usando sintaxe Snowflake JSON_DATA:campo::TIPO
    JSON_DATA:IDCLIENTE::NUMBER AS IDCLIENTE,
    JSON_DATA:IDTIPOPESSOA::NUMBER AS IDTIPOPESSOA,
    JSON_DATA:IDCONJUGE::NUMBER AS IDCONJUGE,
    JSON_DATA:IDEMPRESACLIENTEPF::NUMBER AS IDEMPRESACLIENTEPF,
    JSON_DATA:IDENDERECO::NUMBER AS IDENDERECO,
    JSON_DATA:IDESTABELECIMENTO::NUMBER AS IDESTABELECIMENTO,
    JSON_DATA:IDLIMITECREDITO::NUMBER AS IDLIMITECREDITO,
    JSON_DATA:IDTAMANHOCALCADO::NUMBER AS IDTAMANHOCALCADO,
    JSON_DATA:IDTIMEDEFUTEBOL::NUMBER AS IDTIMEDEFUTEBOL,
    JSON_DATA:IDULTIMOHISTORICOPESQUISASPC::NUMBER AS IDULTIMOHISTORICOPESQUISASPC,
    JSON_DATA:IDTIPOCADASTRO::NUMBER AS IDTIPOCADASTRO,
    JSON_DATA:IDATIVIDADE::NUMBER AS IDATIVIDADE,
    JSON_DATA:IDANALISECREDITO::NUMBER AS IDANALISECREDITO,
    JSON_DATA:IDESTADOCIVIL::NUMBER AS IDESTADOCIVIL,
    JSON_DATA:STATUS::VARCHAR AS STATUS,
    JSON_DATA:CPFCNPJ::VARCHAR AS CPFCNPJ,
    JSON_DATA:RG::VARCHAR AS RG,
    JSON_DATA:RGESTADO::VARCHAR AS RGESTADO,
    JSON_DATA:NOME::VARCHAR AS NOME,
    JSON_DATA:NOMEREDUZIDO::VARCHAR AS NOMEREDUZIDO,
    JSON_DATA:SEXO::VARCHAR AS SEXO,
    JSON_DATA:MAE::VARCHAR AS MAE,
    JSON_DATA:PAI::VARCHAR AS PAI,
    JSON_DATA:ETNIA::VARCHAR AS ETNIA,
    JSON_DATA:INSCRICAOESTADUAL::VARCHAR AS INSCRICAOESTADUAL,
    JSON_DATA:DATACADASTRO::TIMESTAMP_NTZ AS DATACADASTRO,
    JSON_DATA:DATANASCIMENTO::TIMESTAMP_NTZ AS DATANASCIMENTO,
    JSON_DATA:DATAPRIMEIRACOMPRANOLIMITE::TIMESTAMP_NTZ AS DATAPRIMEIRACOMPRANOLIMITE,
    JSON_DATA:DATAULTIMAATUALIZACAO::TIMESTAMP_NTZ AS DATAULTIMAATUALIZACAO,
    JSON_DATA:DATAULTIMACOMPRA::TIMESTAMP_NTZ AS DATAULTIMACOMPRA,
    JSON_DATA:DIVULGAREMAIL::VARCHAR AS DIVULGAREMAIL,
    JSON_DATA:ISRENDACOMPROVADA::VARCHAR AS ISRENDACOMPROVADA,
    JSON_DATA:PONTUACAOANTIGA::NUMBER AS PONTUACAOANTIGA,
    JSON_DATA:POSSUIEMAIL::VARCHAR AS POSSUIEMAIL,
    JSON_DATA:VALORRENDA::NUMBER AS VALORRENDA,
    JSON_DATA:QTDCARNESPAGOEMATRASO::NUMBER AS QTDCARNESPAGOEMATRASO,
    JSON_DATA:QTDCHEQUESDEVOLVIDOS::NUMBER AS QTDCHEQUESDEVOLVIDOS,
    JSON_DATA:QTDCHEQUESPAGOEMATRASO::NUMBER AS QTDCHEQUESPAGOEMATRASO,
    JSON_DATA:QTDCOMPRASREALIZADAS::NUMBER AS QTDCOMPRASREALIZADAS,
    JSON_DATA:VALORCARNESPAGOEMATRASO::NUMBER AS VALORCARNESPAGOEMATRASO,
    JSON_DATA:VALORCHEQUESDEVOLVIDOS::NUMBER AS VALORCHEQUESDEVOLVIDOS,
    JSON_DATA:VALORCHEQUESPAGOEMATRASO::NUMBER AS VALORCHEQUESPAGOEMATRASO,
    JSON_DATA:VALORMAXIMOCOMPRADO::NUMBER AS VALORMAXIMOCOMPRADO,
    JSON_DATA:VALORTOTALCOMPRADO::NUMBER AS VALORTOTALCOMPRADO,
    JSON_DATA:VALORULTIMACOMPRA::NUMBER AS VALORULTIMACOMPRA,
    JSON_DATA:OBSERVACAO::VARCHAR AS OBSERVACAO,
    JSON_DATA:CODIGOAB::NUMBER AS CODIGOAB,
    JSON_DATA:DESABILITARABANDONAR::VARCHAR AS DESABILITARABANDONAR,
    JSON_DATA:IDULTIMOHISTORICOSPCSCORE::NUMBER AS IDULTIMOHISTORICOSPCSCORE,
    JSON_DATA:IDCICLO::NUMBER AS IDCICLO,
    JSON_DATA:CADASTRADOCARDS::VARCHAR AS CADASTRADOCARDS,
    JSON_DATA:CONTRIBUINTEICMS::VARCHAR AS CONTRIBUINTEICMS,
    JSON_DATA:RENDACOMPROVADA::VARCHAR AS RENDACOMPROVADA,
    JSON_DATA:GRUPOORIGEM::VARCHAR AS GRUPOORIGEM,
    JSON_DATA:MIGRADOFOTO::VARCHAR AS MIGRADOFOTO,
    JSON_DATA:MIGRADOIZIO::NUMBER AS MIGRADOIZIO,
    JSON_DATA:IDOCUPACAO::NUMBER AS IDOCUPACAO,
    JSON_DATA:SITUACAOEMPREGATICIA::NUMBER AS SITUACAOEMPREGATICIA,
    JSON_DATA:UTILIZAOVERLIMITFESTCLUB::VARCHAR AS UTILIZAOVERLIMITFESTCLUB,
    JSON_DATA:CODIGOPRODUTOOSCAR::NUMBER AS CODIGOPRODUTOOSCAR,
    JSON_DATA:CODIGOPRODUTOJO::NUMBER AS CODIGOPRODUTOJO,
    JSON_DATA:FATURADIGITALTIPO::VARCHAR AS FATURADIGITALTIPO,
    JSON_DATA:ORGAOEMISSOR::VARCHAR AS ORGAOEMISSOR,
    JSON_DATA:CIDADENATAL::VARCHAR AS CIDADENATAL,
    JSON_DATA:UFNATAL::VARCHAR AS UFNATAL,
    JSON_DATA:DATAEMISSAODOCUMENTO::TIMESTAMP_NTZ AS DATAEMISSAODOCUMENTO,
    JSON_DATA:INTEGRADOR::VARCHAR AS INTEGRADOR,
    JSON_DATA:RECEBERWHATSAPP::VARCHAR AS RECEBERWHATSAPP,
    JSON_DATA:CODIGOPRODUTOABYS::NUMBER AS CODIGOPRODUTOABYS,
    JSON_DATA:POSSUISENHAPADRAO::VARCHAR AS POSSUISENHAPADRAO,
    JSON_DATA:CODIGOEXTERNO::VARCHAR AS CODIGOEXTERNO,
    JSON_DATA:CADASTRADOPOINTUS::VARCHAR AS CADASTRADOPOINTUS,
    JSON_DATA:CODIGOPRODUTOCARIOCA::NUMBER AS CODIGOPRODUTOCARIOCA,
    JSON_DATA:CODIGOPRODUTO::NUMBER AS CODIGOPRODUTO,
    JSON_DATA:ISFIDELIDADEPOINTUS::VARCHAR AS ISFIDELIDADEPOINTUS,
    JSON_DATA:PINSUFRAMA::NUMBER AS PINSUFRAMA,
    JSON_DATA:FIDELIDADEPOINTUS::VARCHAR AS FIDELIDADEPOINTUS,
    JSON_DATA:_DMS_LOADED_AT::TIMESTAMP_NTZ AS _DMS_LOADED_AT,
    
    -- Metadados preservados para auditoria e rastreabilidade
    S3_FILE_NAME,              -- Arquivo de origem no S3
    S3_FILE_ROW_NUMBER,        -- Posição no arquivo original
    S3_FILE_LAST_MODIFIED,     -- Quando o arquivo foi modificado
    LOAD_TIMESTAMP_UTC,        -- Quando foi carregado no Snowflake
    RECORD_SOURCE              -- Sistema/processo de origem
    
FROM raw_data