{{
  config(
    materialized = 'view'
  ) 
}}

WITH raw_data AS (
    SELECT
        JSON_DATA,                  -- Campo VARIANT contendo o JSON completo
        S3_FILE_NAME,              -- Nome do arquivo S3 de origem
        S3_FILE_ROW_NUMBER,        -- Número da linha no arquivo original
        S3_FILE_LAST_MODIFIED,     -- Timestamp de modificação do arquivo S3
        LOAD_TIMESTAMP_UTC,        -- Timestamp de quando foi carregado no Snowflake
        RECORD_SOURCE              -- Identificador da fonte do registro
    FROM {{ source('raw_json', 'jsn_mstore_t_notafiscal') }}
)

SELECT
    -- Colunas extraídas do JSON usando sintaxe Snowflake JSON_DATA:campo::TIPO
    JSON_DATA:IDNOTAFISCAL::NUMBER AS IDNOTAFISCAL,
    JSON_DATA:NUMERONOTA::VARCHAR AS NUMERONOTA,
    JSON_DATA:ICMS::NUMBER AS ICMS,
    JSON_DATA:VALORBASEICMS::NUMBER AS VALORBASEICMS,
    JSON_DATA:VALORICMS::NUMBER AS VALORICMS,
    JSON_DATA:VALORBASEICMSSUBSTITUICAO::NUMBER AS VALORBASEICMSSUBSTITUICAO,
    JSON_DATA:VALORICMSSUBSTITUICAO::NUMBER AS VALORICMSSUBSTITUICAO,
    JSON_DATA:VALORTOTALPRODUTOS::NUMBER AS VALORTOTALPRODUTOS,
    JSON_DATA:VALORFRETE::NUMBER AS VALORFRETE,
    JSON_DATA:VALORSEGURO::NUMBER AS VALORSEGURO,
    JSON_DATA:OUTRASDESPESAS::NUMBER AS OUTRASDESPESAS,
    JSON_DATA:VALORTOTALIPI::NUMBER AS VALORTOTALIPI,
    JSON_DATA:VALORTOTALNOTA::NUMBER AS VALORTOTALNOTA,
    JSON_DATA:OBSERVACAO::VARCHAR AS OBSERVACAO,
    JSON_DATA:DATA::TIMESTAMP_NTZ AS DATA,
    JSON_DATA:IDESTABELECIMENTO::NUMBER AS IDESTABELECIMENTO,
    JSON_DATA:DATAEMISSAO::TIMESTAMP_NTZ AS DATAEMISSAO,
    JSON_DATA:DATACONFIRMACAO::TIMESTAMP_NTZ AS DATACONFIRMACAO,
    JSON_DATA:IDUSUARIOCONFIRMACAO::NUMBER AS IDUSUARIOCONFIRMACAO,
    JSON_DATA:IDCONHECIMENTO::NUMBER AS IDCONHECIMENTO,
    JSON_DATA:JAALTEROUCODIGOBARRA::VARCHAR AS JAALTEROUCODIGOBARRA,
    JSON_DATA:IDUSUARIOCADASTRO::NUMBER AS IDUSUARIOCADASTRO,
    JSON_DATA:DIVERGENCIAS::VARCHAR AS DIVERGENCIAS,
    JSON_DATA:IDUSUARIOCANCELAMENTO::NUMBER AS IDUSUARIOCANCELAMENTO,
    JSON_DATA:DATACANCELAMENTO::TIMESTAMP_NTZ AS DATACANCELAMENTO,
    JSON_DATA:STATUS::VARCHAR AS STATUS,
    JSON_DATA:PORCENTAGEMDESCONTO::NUMBER AS PORCENTAGEMDESCONTO,
    JSON_DATA:DESCRICAODIVERGENCIAS::VARCHAR AS DESCRICAODIVERGENCIAS,
    JSON_DATA:NOTACARTEIRA::VARCHAR AS NOTACARTEIRA,
    JSON_DATA:TIPOIPI::VARCHAR AS TIPOIPI,
    JSON_DATA:IDFORNECEDOR::NUMBER AS IDFORNECEDOR,
    JSON_DATA:CNPJ::VARCHAR AS CNPJ,
    JSON_DATA:CODIGOAB::NUMBER AS CODIGOAB,
    JSON_DATA:NUMERONFE::VARCHAR AS NUMERONFE,
    JSON_DATA:PORCENTAGEMDEREDUCAODEBASE::NUMBER AS PORCENTAGEMDEREDUCAODEBASE,
    JSON_DATA:USADONFEDEVOLUCAO::VARCHAR AS USADONFEDEVOLUCAO,
    JSON_DATA:ISBONIFICADO::VARCHAR AS ISBONIFICADO,
    JSON_DATA:SERIE::VARCHAR AS SERIE,
    JSON_DATA:_DMS_LOADED_AT::TIMESTAMP_NTZ AS _DMS_LOADED_AT,
    
    -- Metadados preservados para auditoria e rastreabilidade
    S3_FILE_NAME,              -- Arquivo de origem no S3
    S3_FILE_ROW_NUMBER,        -- Posição no arquivo original
    S3_FILE_LAST_MODIFIED,     -- Quando o arquivo foi modificado
    LOAD_TIMESTAMP_UTC,        -- Quando foi carregado no Snowflake
    RECORD_SOURCE              -- Sistema/processo de origem
    
FROM raw_data