{{
  config(
    materialized = 'view'
  ) 
}}

WITH raw_data AS (
    SELECT
        JSON_DATA,                  -- Campo VARIANT contendo o JSON completo
        S3_FILE_NAME,              -- Nome do arquivo S3 de origem
        S3_FILE_ROW_NUMBER,        -- Número da linha no arquivo original
        S3_FILE_LAST_MODIFIED,     -- Timestamp de modificação do arquivo S3
        LOAD_TIMESTAMP_UTC,        -- Timestamp de quando foi carregado no Snowflake
        RECORD_SOURCE              -- Identificador da fonte do registro
    FROM {{ source('raw_json', 'jsn_mstore_t_referenciaproduto') }}
)

SELECT
    -- Colunas extraídas do JSON usando sintaxe Snowflake JSON_DATA:campo::TIPO
    JSON_DATA:IDREFERENCIAPRODUTO::NUMBER AS IDREFERENCIAPRODUTO,
    JSON_DATA:REFERENCIA::VARCHAR AS REFERENCIA,
    JSON_DATA:IDGRUPOPRODUTO::NUMBER AS IDGRUPOPRODUTO,
    JSON_DATA:IDPRODUTOGENERICO::NUMBER AS IDPRODUTOGENERICO,
    JSON_DATA:IDPRODUTOESPECIFICO::NUMBER AS IDPRODUTOESPECIFICO,
    JSON_DATA:IDMARCA::NUMBER AS IDMARCA,
    JSON_DATA:IDMATERIAL::NUMBER AS IDMATERIAL,
    JSON_DATA:IDUNIDADE::NUMBER AS IDUNIDADE,
    JSON_DATA:IDCOMPRADOR::NUMBER AS IDCOMPRADOR,
    JSON_DATA:TIPONACIONALIDADE::VARCHAR AS TIPONACIONALIDADE,
    JSON_DATA:TIPOCODIGOBARRA::NUMBER AS TIPOCODIGOBARRA,
    JSON_DATA:IDSECAO::NUMBER AS IDSECAO,
    JSON_DATA:DESCRICAORESUMIDA::VARCHAR AS DESCRICAORESUMIDA,
    JSON_DATA:STATUS::VARCHAR AS STATUS,
    JSON_DATA:IDGRADE::NUMBER AS IDGRADE,
    JSON_DATA:IDTRIBUTACAO::NUMBER AS IDTRIBUTACAO,
    JSON_DATA:IDFORNECEDOR::NUMBER AS IDFORNECEDOR,
    JSON_DATA:CODIGOAB::NUMBER AS CODIGOAB,
    JSON_DATA:SUBSTITUICAOTRIBUTARIA::VARCHAR AS SUBSTITUICAOTRIBUTARIA,
    JSON_DATA:NCM::VARCHAR AS NCM,
    JSON_DATA:ORIGEMPRODUTO::VARCHAR AS ORIGEMPRODUTO,
    JSON_DATA:REDUCAOBASEICMS::NUMBER AS REDUCAOBASEICMS,
    JSON_DATA:TIPO::VARCHAR AS TIPO,
    JSON_DATA:CEST::VARCHAR AS CEST,
    JSON_DATA:URLECOMMERCE::VARCHAR AS URLECOMMERCE,
    JSON_DATA:DATACADASTRO::TIMESTAMP_NTZ AS DATACADASTRO,
    JSON_DATA:DATAPRIMEIRAENTRADA::TIMESTAMP_NTZ AS DATAPRIMEIRAENTRADA,
    JSON_DATA:STATUSPRODUTONOVO::VARCHAR AS STATUSPRODUTONOVO,
    JSON_DATA:DATAPRODUTOANTIGO::TIMESTAMP_NTZ AS DATAPRODUTOANTIGO,
    JSON_DATA:CODIGOEXTERNO::VARCHAR AS CODIGOEXTERNO,
    JSON_DATA:PRODUTODIADORA::NUMBER AS PRODUTODIADORA,
    JSON_DATA:CODIGOEXTERNOPAQUETA::VARCHAR AS CODIGOEXTERNOPAQUETA,
    JSON_DATA:CSTPISCOFINSVENDA::VARCHAR AS CSTPISCOFINSVENDA,
    JSON_DATA:CSTPISCOFINSREMESSA::VARCHAR AS CSTPISCOFINSREMESSA,
    JSON_DATA:_DMS_LOADED_AT::TIMESTAMP_NTZ AS _DMS_LOADED_AT,
    
    -- Metadados preservados para auditoria e rastreabilidade
    S3_FILE_NAME,              -- Arquivo de origem no S3
    S3_FILE_ROW_NUMBER,        -- Posição no arquivo original
    S3_FILE_LAST_MODIFIED,     -- Quando o arquivo foi modificado
    LOAD_TIMESTAMP_UTC,        -- Quando foi carregado no Snowflake
    RECORD_SOURCE              -- Sistema/processo de origem
    
FROM raw_data