{{
  config(
    materialized = 'view'
  ) 
}}

WITH raw_data AS (
    SELECT
        JSON_DATA,                  -- Campo VARIANT contendo o JSON completo
        S3_FILE_NAME,              -- Nome do arquivo S3 de origem
        S3_FILE_ROW_NUMBER,        -- Número da linha no arquivo original
        S3_FILE_LAST_MODIFIED,     -- Timestamp de modificação do arquivo S3
        LOAD_TIMESTAMP_UTC,        -- Timestamp de quando foi carregado no Snowflake
        RECORD_SOURCE              -- Identificador da fonte do registro
    FROM {{ source('raw_json', 'jsn_mstore_t_orcamento') }}
)

SELECT
    -- Colunas extraídas do JSON usando sintaxe Snowflake JSON_DATA:campo::TIPO
    JSON_DATA:IDORCAMENTO::NUMBER AS IDORCAMENTO,
    JSON_DATA:STATUS::VARCHAR AS STATUS,
    JSON_DATA:DATA::TIMESTAMP_NTZ AS DATA,
    JSON_DATA:TEMPO::NUMBER AS TEMPO,
    JSON_DATA:OBSERVACAO::VARCHAR AS OBSERVACAO,
    JSON_DATA:IDVENDEDOR::NUMBER AS IDVENDEDOR,
    JSON_DATA:DESCONTOPERCENTUAL::NUMBER AS DESCONTOPERCENTUAL,
    JSON_DATA:DESCONTOVALOR::NUMBER AS DESCONTOVALOR,
    JSON_DATA:TOTALDEPECAS::NUMBER AS TOTALDEPECAS,
    JSON_DATA:VALORBRUTO::NUMBER AS VALORBRUTO,
    JSON_DATA:VALOR::NUMBER AS VALOR,
    JSON_DATA:IDUSUARIO::NUMBER AS IDUSUARIO,
    JSON_DATA:IDUSUARIOAUTORIZACAO::NUMBER AS IDUSUARIOAUTORIZACAO,
    JSON_DATA:IDUSUARIOCANCELAMENTO::NUMBER AS IDUSUARIOCANCELAMENTO,
    JSON_DATA:DATACANCELAMENTO::TIMESTAMP_NTZ AS DATACANCELAMENTO,
    JSON_DATA:IDESTABELECIMENTO::NUMBER AS IDESTABELECIMENTO,
    JSON_DATA:IDPONTOVENDA::NUMBER AS IDPONTOVENDA,
    JSON_DATA:VALEFUNCIONARIO::VARCHAR AS VALEFUNCIONARIO,
    JSON_DATA:NOMECLIENTE::VARCHAR AS NOMECLIENTE,
    JSON_DATA:IDCONDICAOPAGAMENTO::NUMBER AS IDCONDICAOPAGAMENTO,
    JSON_DATA:PERFILCLIENTE::NUMBER AS PERFILCLIENTE,
    JSON_DATA:IDTROCA::NUMBER AS IDTROCA,
    JSON_DATA:OBSERVACAOCANCELAMENTO::VARCHAR AS OBSERVACAOCANCELAMENTO,
    JSON_DATA:ACRESCIMOPERCENTUAL::NUMBER AS ACRESCIMOPERCENTUAL,
    JSON_DATA:CODIGOCONDICAOPAGAMENTOCARDS::NUMBER AS CODIGOCONDICAOPAGAMENTOCARDS,
    JSON_DATA:DESCRICONDICAOPAGAMENTOCARDS::VARCHAR AS DESCRICONDICAOPAGAMENTOCARDS,
    JSON_DATA:RETIRADODOESTOQUE::VARCHAR AS RETIRADODOESTOQUE,
    JSON_DATA:IDCAIXA::NUMBER AS IDCAIXA,
    JSON_DATA:IDVENDA::VARCHAR AS IDVENDA,
    JSON_DATA:IDCLIENTE::NUMBER AS IDCLIENTE,
    JSON_DATA:IDUSUARIOCAIXA::NUMBER AS IDUSUARIOCAIXA,
    JSON_DATA:DATACONFIRMACAO::TIMESTAMP_NTZ AS DATACONFIRMACAO,
    JSON_DATA:CODIGOAB::NUMBER AS CODIGOAB,
    JSON_DATA:CPFCNPJ::VARCHAR AS CPFCNPJ,
    JSON_DATA:IDULTIMOHISTORICOSPCSCORE::NUMBER AS IDULTIMOHISTORICOSPCSCORE,
    JSON_DATA:IDULTIMOHISTORICOPESQUISASPC::NUMBER AS IDULTIMOHISTORICOPESQUISASPC,
    JSON_DATA:TICKET::VARCHAR AS TICKET,
    JSON_DATA:STATUSCONFERENCIA::VARCHAR AS STATUSCONFERENCIA,
    JSON_DATA:IDUSUARIOCONFERENCIA::NUMBER AS IDUSUARIOCONFERENCIA,
    JSON_DATA:VALORCUPOMDESCONTO::NUMBER AS VALORCUPOMDESCONTO,
    JSON_DATA:VALORFRETE::NUMBER AS VALORFRETE,
    JSON_DATA:CHAVESEGURANCA::VARCHAR AS CHAVESEGURANCA,
    JSON_DATA:CODIGOVALEFUNCIONARIO::NUMBER AS CODIGOVALEFUNCIONARIO,
    JSON_DATA:CPFCNPJDEPENDENTE::VARCHAR AS CPFCNPJDEPENDENTE,
    JSON_DATA:VALORKITDESCONTO::NUMBER AS VALORKITDESCONTO,
    JSON_DATA:IDCUPOMDESCONTOCLIENTE::NUMBER AS IDCUPOMDESCONTOCLIENTE,
    JSON_DATA:VALORCASHBACK::NUMBER AS VALORCASHBACK,
    JSON_DATA:AUTOATENDIMENTO::VARCHAR AS AUTOATENDIMENTO,
    JSON_DATA:TIPOCUPOMDESCONTO::NUMBER AS TIPOCUPOMDESCONTO,
    JSON_DATA:IDTRANSACAOSOLUCX::VARCHAR AS IDTRANSACAOSOLUCX,
    JSON_DATA:ORCAMENTOEDITADOFLAG::VARCHAR AS ORCAMENTOEDITADOFLAG,
    JSON_DATA:ORCAMENTOWEBSTOREFLAG::VARCHAR AS ORCAMENTOWEBSTOREFLAG,
    JSON_DATA:INTEGRADOR::VARCHAR AS INTEGRADOR,
    JSON_DATA:ORCAMENTOBAIXADO::VARCHAR AS ORCAMENTOBAIXADO,
    JSON_DATA:IDLOJAVENDEDOR::NUMBER AS IDLOJAVENDEDOR,
    JSON_DATA:CODIGOEXTERNO::VARCHAR AS CODIGOEXTERNO,
    JSON_DATA:DESCONTOFIDELIDADE::NUMBER AS DESCONTOFIDELIDADE,
    JSON_DATA:CODIGORESGATEFIDELIDADE::VARCHAR AS CODIGORESGATEFIDELIDADE,
    JSON_DATA:STATUSRESGATEFIDELIDADE::VARCHAR AS STATUSRESGATEFIDELIDADE,
    JSON_DATA:PEDIDOECOMMERCE::VARCHAR AS PEDIDOECOMMERCE,
    JSON_DATA:_DMS_LOADED_AT::TIMESTAMP_NTZ AS _DMS_LOADED_AT,
    
    -- Metadados preservados para auditoria e rastreabilidade
    S3_FILE_NAME,              -- Arquivo de origem no S3
    S3_FILE_ROW_NUMBER,        -- Posição no arquivo original
    S3_FILE_LAST_MODIFIED,     -- Quando o arquivo foi modificado
    LOAD_TIMESTAMP_UTC,        -- Quando foi carregado no Snowflake
    RECORD_SOURCE              -- Sistema/processo de origem
    
FROM raw_data