{{
  config(
    materialized = 'view'
  ) 
}}

WITH raw_data AS (
    SELECT
        JSON_DATA,                  -- Campo VARIANT contendo o JSON completo
        S3_FILE_NAME,              -- Nome do arquivo S3 de origem
        S3_FILE_ROW_NUMBER,        -- Número da linha no arquivo original
        S3_FILE_LAST_MODIFIED,     -- Timestamp de modificação do arquivo S3
        LOAD_TIMESTAMP_UTC,        -- Timestamp de quando foi carregado no Snowflake
        RECORD_SOURCE              -- Identificador da fonte do registro
    FROM {{ source('raw_json', 'jsn_mstore_t_orcamentoproduto') }}
)

SELECT
    -- Colunas extraídas do JSON usando sintaxe Snowflake JSON_DATA:campo::TIPO
    JSON_DATA:IDORCAMENTOPRODUTO::NUMBER AS IDORCAMENTOPRODUTO,
    JSON_DATA:VALORVENDA::NUMBER AS VALORVENDA,
    JSON_DATA:IDORCAMENTO::NUMBER AS IDORCAMENTO,
    JSON_DATA:QUANTIDADE::NUMBER AS QUANTIDADE,
    JSON_DATA:IDPRODUTO::NUMBER AS IDPRODUTO,
    JSON_DATA:VALORCUSTO::NUMBER AS VALORCUSTO,
    JSON_DATA:DESCONTOVALOR::NUMBER AS DESCONTOVALOR,
    JSON_DATA:FORADELINHA::VARCHAR AS FORADELINHA,
    JSON_DATA:PREMIO::NUMBER AS PREMIO,
    JSON_DATA:CLOSEOUT::VARCHAR AS CLOSEOUT,
    JSON_DATA:CODIGOAB::NUMBER AS CODIGOAB,
    JSON_DATA:RETIRADODOESTOQUEPELATROCA::VARCHAR AS RETIRADODOESTOQUEPELATROCA,
    JSON_DATA:CONFERIDO::VARCHAR AS CONFERIDO,
    JSON_DATA:EHPRESENTE::VARCHAR AS EHPRESENTE,
    JSON_DATA:VALORKITDESCONTO::NUMBER AS VALORKITDESCONTO,
    JSON_DATA:EHKITPRODUTO::VARCHAR AS EHKITPRODUTO,
    JSON_DATA:TIPOKITPRODUTOAPLICADO::NUMBER AS TIPOKITPRODUTOAPLICADO,
    JSON_DATA:AGRUPAMENTOPRESENTE::VARCHAR AS AGRUPAMENTOPRESENTE,
    JSON_DATA:EHBRINDE::VARCHAR AS EHBRINDE,
    JSON_DATA:VALORCASHBACK::NUMBER AS VALORCASHBACK,
    JSON_DATA:EHKITPRODUTOBRINDE::VARCHAR AS EHKITPRODUTOBRINDE,
    JSON_DATA:TIPOKITPRODUTO::NUMBER AS TIPOKITPRODUTO,
    JSON_DATA:VALORCUPOMDESCONTO::NUMBER AS VALORCUPOMDESCONTO,
    JSON_DATA:STATUSPRODUTONOVO::VARCHAR AS STATUSPRODUTONOVO,
    JSON_DATA:VALORDESCONTOFUNCIONARIO::NUMBER AS VALORDESCONTOFUNCIONARIO,
    JSON_DATA:FRETERATEADO::NUMBER AS FRETERATEADO,
    JSON_DATA:CODIGOEXTERNO::VARCHAR AS CODIGOEXTERNO,
    JSON_DATA:CUSTOMEDIOPRODUTO::NUMBER AS CUSTOMEDIOPRODUTO,
    JSON_DATA:CUSTOMEDIOPRODUTOCONSOLIDADO::NUMBER AS CUSTOMEDIOPRODUTOCONSOLIDADO,
    JSON_DATA:_DMS_LOADED_AT::TIMESTAMP_NTZ AS _DMS_LOADED_AT,
    
    -- Metadados preservados para auditoria e rastreabilidade
    S3_FILE_NAME,              -- Arquivo de origem no S3
    S3_FILE_ROW_NUMBER,        -- Posição no arquivo original
    S3_FILE_LAST_MODIFIED,     -- Quando o arquivo foi modificado
    LOAD_TIMESTAMP_UTC,        -- Quando foi carregado no Snowflake
    RECORD_SOURCE              -- Sistema/processo de origem
    
FROM raw_data