{{
  config(
    materialized = 'view'
  ) 
}}

WITH raw_data AS (
    SELECT
        JSON_DATA,                  -- Campo VARIANT contendo o JSON completo
        S3_FILE_NAME,              -- Nome do arquivo S3 de origem
        S3_FILE_ROW_NUMBER,        -- Número da linha no arquivo original
        S3_FILE_LAST_MODIFIED,     -- Timestamp de modificação do arquivo S3
        LOAD_TIMESTAMP_UTC,        -- Timestamp de quando foi carregado no Snowflake
        RECORD_SOURCE              -- Identificador da fonte do registro
    FROM {{ source('raw_json', 'jsn_mstore_t_funcionario') }}
)

SELECT
    -- Colunas extraídas do JSON usando sintaxe Snowflake JSON_DATA:campo::TIPO
    JSON_DATA:IDFUNCIONARIO::NUMBER AS IDFUNCIONARIO,
    JSON_DATA:COMISSAOACIMAMETA::NUMBER AS COMISSAOACIMAMETA,
    JSON_DATA:COMISSAOENTREMETAS::NUMBER AS COMISSAOENTREMETAS,
    JSON_DATA:COMISSAOABAIXOMETA::NUMBER AS COMISSAOABAIXOMETA,
    JSON_DATA:LIMITECOMPRAS::NUMBER AS LIMITECOMPRAS,
    JSON_DATA:COMPRASREALIZADAS::NUMBER AS COMPRASREALIZADAS,
    JSON_DATA:PORCENTAGEMMAXIMADESCONTO::NUMBER AS PORCENTAGEMMAXIMADESCONTO,
    JSON_DATA:IDUSUARIO::NUMBER AS IDUSUARIO,
    JSON_DATA:IDESTABELECIMENTO::NUMBER AS IDESTABELECIMENTO,
    JSON_DATA:SALARIO::NUMBER AS SALARIO,
    JSON_DATA:DATANASCIMENTO::TIMESTAMP_NTZ AS DATANASCIMENTO,
    JSON_DATA:CPF::VARCHAR AS CPF,
    JSON_DATA:CONJUGE::VARCHAR AS CONJUGE,
    JSON_DATA:MAE::VARCHAR AS MAE,
    JSON_DATA:PAI::VARCHAR AS PAI,
    JSON_DATA:SEXO::VARCHAR AS SEXO,
    JSON_DATA:RG::VARCHAR AS RG,
    JSON_DATA:IDATIVIDADE::NUMBER AS IDATIVIDADE,
    JSON_DATA:NOME::VARCHAR AS NOME,
    JSON_DATA:NOMEREDUZIDO::VARCHAR AS NOMEREDUZIDO,
    JSON_DATA:OBSERVACAO::VARCHAR AS OBSERVACAO,
    JSON_DATA:IDENDERECO::NUMBER AS IDENDERECO,
    JSON_DATA:STATUS::VARCHAR AS STATUS,
    JSON_DATA:IDFUNCIONARIOOLD::VARCHAR AS IDFUNCIONARIOOLD,
    JSON_DATA:IDESTADOCIVIL::NUMBER AS IDESTADOCIVIL,
    JSON_DATA:CODIGOAB::NUMBER AS CODIGOAB,
    JSON_DATA:CENTRODECUSTO::VARCHAR AS CENTRODECUSTO,
    JSON_DATA:CADASTRADOCONTADIGITAL::VARCHAR AS CADASTRADOCONTADIGITAL,
    JSON_DATA:ATUALIZACADASTROBEEHOME::VARCHAR AS ATUALIZACADASTROBEEHOME,
    JSON_DATA:CODIGOEXTERNO::VARCHAR AS CODIGOEXTERNO,
    JSON_DATA:IDCADASTROBEEHOME::NUMBER AS IDCADASTROBEEHOME,
    JSON_DATA:DATAADMISSAO::TIMESTAMP_NTZ AS DATAADMISSAO,
    JSON_DATA:ISBACKOFFICE::VARCHAR AS ISBACKOFFICE,
    JSON_DATA:_DMS_LOADED_AT::TIMESTAMP_NTZ AS _DMS_LOADED_AT,
    
    -- Metadados preservados para auditoria e rastreabilidade
    S3_FILE_NAME,              -- Arquivo de origem no S3
    S3_FILE_ROW_NUMBER,        -- Posição no arquivo original
    S3_FILE_LAST_MODIFIED,     -- Quando o arquivo foi modificado
    LOAD_TIMESTAMP_UTC,        -- Quando foi carregado no Snowflake
    RECORD_SOURCE              -- Sistema/processo de origem
    
FROM raw_data