{{
  config(
    materialized = 'view'
  ) 
}}

WITH raw_data AS (
    SELECT
        JSON_DATA,                  -- Campo VARIANT contendo o JSON completo
        S3_FILE_NAME,              -- Nome do arquivo S3 de origem
        S3_FILE_ROW_NUMBER,        -- Número da linha no arquivo original
        S3_FILE_LAST_MODIFIED,     -- Timestamp de modificação do arquivo S3
        LOAD_TIMESTAMP_UTC,        -- Timestamp de quando foi carregado no Snowflake
        RECORD_SOURCE              -- Identificador da fonte do registro
    FROM {{ source('raw_json', 'jsn_mstore_t_produto') }}
)

SELECT
    -- Colunas extraídas do JSON usando sintaxe Snowflake JSON_DATA:campo::TIPO
    JSON_DATA:IDPRODUTO::NUMBER AS IDPRODUTO,
    JSON_DATA:DATAULTIMAVENDA::TIMESTAMP_NTZ AS DATAULTIMAVENDA,
    JSON_DATA:DATAULTIMAENTRADA::TIMESTAMP_NTZ AS DATAULTIMAENTRADA,
    JSON_DATA:FORADELINHA::VARCHAR AS FORADELINHA,
    JSON_DATA:NOME::VARCHAR AS NOME,
    JSON_DATA:NOMEIMPRESSAO::VARCHAR AS NOMEIMPRESSAO,
    JSON_DATA:IDREFERENCIAPRODUTO::NUMBER AS IDREFERENCIAPRODUTO,
    JSON_DATA:IDCOR::NUMBER AS IDCOR,
    JSON_DATA:IDTAMANHO::NUMBER AS IDTAMANHO,
    JSON_DATA:VALORCUSTO::NUMBER AS VALORCUSTO,
    JSON_DATA:VALORCOMFRETE::NUMBER AS VALORCOMFRETE,
    JSON_DATA:PRECOBASE::NUMBER AS PRECOBASE,
    JSON_DATA:DATAFORADELINHA::TIMESTAMP_NTZ AS DATAFORADELINHA,
    JSON_DATA:STATUS::VARCHAR AS STATUS,
    JSON_DATA:IDPRODUTO_OLD::NUMBER AS IDPRODUTO_OLD,
    JSON_DATA:CODIGOBARRAMIGRACAO::VARCHAR AS CODIGOBARRAMIGRACAO,
    JSON_DATA:DATAULTIMAALTERACAO::TIMESTAMP_NTZ AS DATAULTIMAALTERACAO,
    JSON_DATA:IDCONDPAGULTIMAENTRADA::NUMBER AS IDCONDPAGULTIMAENTRADA,
    JSON_DATA:PREMIO::NUMBER AS PREMIO,
    JSON_DATA:PONTOS::NUMBER AS PONTOS,
    JSON_DATA:CLOSEOUT::VARCHAR AS CLOSEOUT,
    JSON_DATA:DT_ENVIO_ECOMMERCE::TIMESTAMP_NTZ AS DT_ENVIO_ECOMMERCE,
    JSON_DATA:ECOMMERCE::VARCHAR AS ECOMMERCE,
    JSON_DATA:CODIGOAB::NUMBER AS CODIGOAB,
    JSON_DATA:IDDEPARTAMENTO::NUMBER AS IDDEPARTAMENTO,
    JSON_DATA:DATAULTIMAMOVIMENTACAO::TIMESTAMP_NTZ AS DATAULTIMAMOVIMENTACAO,
    JSON_DATA:EAN::VARCHAR AS EAN,
    JSON_DATA:CODIGOALFA::VARCHAR AS CODIGOALFA,
    JSON_DATA:PRECOVENDA::NUMBER AS PRECOVENDA,
    JSON_DATA:PRIMEIROPRECOVENDA::NUMBER AS PRIMEIROPRECOVENDA,
    JSON_DATA:MIGRADOIZIO::NUMBER AS MIGRADOIZIO,
    JSON_DATA:VISIVEL_ECOMMERCE::VARCHAR AS VISIVEL_ECOMMERCE,
    JSON_DATA:VALORCUSTOMEDIO::NUMBER AS VALORCUSTOMEDIO,
    JSON_DATA:CODIGOEXTERNO::VARCHAR AS CODIGOEXTERNO,
    JSON_DATA:CODIGOEXTERNOPAQUETA::VARCHAR AS CODIGOEXTERNOPAQUETA,
    JSON_DATA:SKU_PAQUETA::VARCHAR AS SKU_PAQUETA,
    JSON_DATA:_DMS_LOADED_AT::TIMESTAMP_NTZ AS _DMS_LOADED_AT,
    
    -- Metadados preservados para auditoria e rastreabilidade
    S3_FILE_NAME,              -- Arquivo de origem no S3
    S3_FILE_ROW_NUMBER,        -- Posição no arquivo original
    S3_FILE_LAST_MODIFIED,     -- Quando o arquivo foi modificado
    LOAD_TIMESTAMP_UTC,        -- Quando foi carregado no Snowflake
    RECORD_SOURCE              -- Sistema/processo de origem
    
FROM raw_data